# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env

# Copy csproj and build as distinct layers
COPY roger/  ./

# Copy everything else and build
# COPY ../engine/examples ./
RUN dotnet build \
    dotnet publish -c Release -o out

ENTRYPOINT ["dotnet", "roger.dll"]

# Build runtime image
# FROM mcr.microsoft.com/dotnet/aspnet:6.0
# RUN ls 
# WORKDIR /roger
# COPY --from=build-env /roger/roger/out .
# 